version: "3.9"

services:
  plex-audit:
    build: .
    container_name: plex-audit
    ports:
      - "8787:8787"
    volumes:
      - /volume1/Docker/plex-audit/config:/app/config
      - /volume1/Docker/plex-audit/data:/app/data
    restart: unless-stopped